source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 8.0"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 2.1"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# Hotwire
gem "turbo-rails"
gem "stimulus-rails"

# Vite asset pipeline
gem "vite_rails"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :development do
  gem "web-console"
  gem "error_highlight", ">= 0.4", platforms: :ruby
  gem "foreman"
end
